apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-result-system  # Nombre descriptivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-result-system  # Coherencia en labels
  template:
    metadata:
      labels:
        app: university-result-system  # Mismo label
    spec:
      containers:
      - name: university-webapp      # Nombre del contenedor
        image: university-result-system:1.0  # Nombre de imagen
        imagePullPolicy: Never       # Usar imagen local
        ports:
        - containerPort: 8080        # Puerto del contenedor