apiVersion: v1
kind: Service
metadata:
  name: university-result-service  # Nombre del servicio
spec:
  type: NodePort
  selector:
    app: university-result-system   # Debe coincidir con el deployment
  ports:
    - protocol: TCP
      port: 80                      # Puerto del servicio
      targetPort: 8080              # Puerto del contenedor